export const PAGE = "index.html"

export const API_BASE_URL = process.env.API_BASE_URL

export const ROUTING = {
  OPTIONS_PAGE: "/options",
  SCREEN_CAPTURE_EDITOR: {
    PATH: "/screen-capture/:uuid/",
    PARAM: ":uuid"
  },
  LOGIN_PAGE: "/login",
  REGISTER_PAGE: "/register",
  FORGOT_PASSWORD_PAGE: "/forgot-password",
  TRELLO_PAGE: "/trello",
  POST_PAGE: "/status",
  PROFILE_PAGE: "/profile"
}

export const TRELLO = {
  AUTH_URL: "https://trello.com/1/authorize",
  TOKEN: process.env.TRELLO_TOKEN,
  APP_NAME:  "Screen reporter App",
  RESPONSE_TYPE: "token",
  CALLBACK_METHOD: "fragment",
  SCOPE: "read,write",
  EXPIRATION: 'never' // 1hour, 1day, 30days 
}

export const CAPTURE_OPTIONS = {
  format: 'jpeg'
}

export const CAPTURE_ANNOTATION_OPTIONS = {
  type: "image/jpeg", 
  quality: 1
}

export const ACTIONS = {
  CALL_API: 'CALL_API',
  CALL_STORAGE: 'CALL_STORAGE',
  CALL_TAB: 'CALL_TAB',

  REMOVE_MESSAGES: 'REMOVE_MESSAGES',

  SAVE_ANNOTATED_IMAGE: 'SAVE_ANNOTATED_IMAGE',

  CREATE_ACCOUNT_FAILED: 'CREATE_ACCOUNT_FAILED',
  CREATE_ACCOUNT_SUCCEEDED: 'CREATE_ACCOUNT_SUCCEEDED',

  LOGIN_ACCOUNT_FAILED: 'LOGIN_ACCOUNT_FAILED',
  LOGIN_ACCOUNT_SUCCEDED: 'LOGIN_ACCOUNT_SUCCEDED',

  LOGOUT_ACCOUNT_FAILED: 'LOGOUT_ACCOUNT_FAILED',
  LOGOUT_ACCOUNT_SUCCEDED: 'LOGOUT_ACCOUNT_SUCCEDED',

  FETCH_INTEGRATION_FAILED: 'FETCH_INTEGRATION_FAILED',
  FETCH_INTEGRATION_SUCCEDED: 'FETCH_INTEGRATION_SUCCEDED',

  ADD_INTEGRATION_FAILED: 'ADD_INTEGRATION_FAILED',
  ADD_INTEGRATION_SUCCEDED: 'ADD_INTEGRATION_SUCCEDED',

  EDIT_INTEGRATION_FAILED: 'EDIT_INTEGRATION_FAILED',
  EDIT_INTEGRATION_SUCCEDED: 'EDIT_INTEGRATION_SUCCEDED',

  REMOVE_INTEGRATION_FAILED: 'REMOVE_INTEGRATION_FAILED',
  REMOVE_INTEGRATION_SUCCEDED: 'REMOVE_INTEGRATION_SUCCEDED',

  FETCH_SETTINGS_SUCCEDED: 'FETCH_SETTINGS_SUCCEDED',
  FETCH_SETTINGS_FAILED: 'FETCH_SETTINGS_FAILED',

  EDIT_SETTINGS_FAILED: 'EDIT_SETTINGS_FAILED',
  EDIT_SETTINGS_SUCCEDED: 'EDIT_SETTINGS_SUCCEDED',

  FETCH_SCREENSHOT_SUCCEDED: 'FETCH_SCREENSHOT_SUCCEDED',
  FETCH_SCREENSHOT_FAILED: 'FETCH_SCREENSHOT_FAILED',

  EDIT_SCREENSHOT_SUCCEDED: 'EDIT_SCREENSHOT_SUCCEDED',
  EDIT_SCREENSHOT_FAILED: 'EDIT_SCREENSHOT_FAILED',

  REMOVE_SCREENSHOT_SUCCEDED: 'REMOVE_SCREENSHOT_SUCCEDED',
  REMOVE_SCREENSHOT_FAILED: 'REMOVE_SCREENSHOT_FAILED',

  FETCH_TRELLO_BOARDS_INIT: 'FETCH_TRELLO_BOARDS_INIT',
  FETCH_TRELLO_BOARDS_SUCCEDED: 'FETCH_TRELLO_BOARDS_SUCCEDED',
  FETCH_TRELLO_BOARDS_FAILED: 'FETCH_TRELLO_BOARDS_FAILED',

  FETCH_TRELLO_LISTS_SUCCEDED: 'FETCH_TRELLO_LISTS_SUCCEDED',
  FETCH_TRELLO_LISTS_FAILED: 'FETCH_TRELLO_LISTS_FAILED',

  FETCH_TRELLO_LABELS_SUCCEDED: 'FETCH_TRELLO_LABELS_SUCCEDED',
  FETCH_TRELLO_LABELS_FAILED: 'FETCH_TRELLO_LABELS_FAILED',

  FETCH_TRELLO_MEMBER_SUCCEDED: 'FETCH_TRELLO_MEMBER_SUCCEDED',
  FETCH_TRELLO_MEMBER_FAILED: 'FETCH_TRELLO_MEMBER_FAILED',

  CREATE_TRELLO_CARD_INIT: 'CREATE_TRELLO_CARD_INIT',
  CREATE_TRELLO_CARD_SUCCEDED: 'CREATE_TRELLO_CARD_SUCCEDED',
  CREATE_TRELLO_CARD_FAILED: 'CREATE_TRELLO_CARD_FAILED',

  RESET_PASSWORD_SUCCEDED: 'RESET_PASSWORD_SUCCEDED',
  RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED',

  UPDATE_ACCOUNT_SUCCEDED: 'UPDATE_ACCOUNT_SUCCEDED',
  UPDATE_ACCOUNT_FAILED: 'UPDATE_ACCOUNT_FAILED'
}


export const HTTP_METHODS = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE'
}


export const ENDPOINT = {
  REGISTER: '/api/auth/register',
  LOGIN: '/api/auth/login',
  LOGOUT: '/api/auth/logout',
  INTEGRATIONS: '/api/integrations',
  USER: '/api/user/:param',
  INTEGRATION: '/api/integration/:param',
  SETTINGS: '/api/settings',
  RESET: '/api/auth/reset/:param',
  TRELLO: {
    BOARDS: '/api/trello/boards',
    LISTS: '/api/trello/board/:param/lists',
    MEMBERS: '/api/trello/board/:param/members',
    LABELS: '/api/trello/board/:param/labels',
    CREATE_CARD: '/api/trello/create-card'
  }
}


export const STORAGE = {
  STORE: "STORE_STORAGE_KEY",
  SCREEN_CAPTURE: "SCREEN_CAPTURE_STORAGE_KEY"
}


export const STORAGE_METHODS = {
  SET_ITEM: "SET_ITEM", 
  GET_ITEM: "GET_ITEM",
  EDIT_ITEM: "EDIT_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM"
}


export const INIT_STATE = {
  auth: {
    currentUser: null,
    token:null,
    success: null,
    error:null
  },
  integrations: {
    integrationsList: {integrations: [], success: null, error: null},
    trello: { boards: [], labels: [], lists: [], members: [], initCardCreation: false, success:null, error:null }
  } ,
  settings: {
    settings: {
      color: 'blue',
      fontsize: '20px',
      linewidth: 5
    },
    success: null,
    error: null
  },
  screenshots: {
    screenshot: null,
    annotatedScreenshot: null,
    error: null
  }
}

